spring.application.name=gateway

# Porta em que a aplicação será executada.
server.port=8080

# URL do Eureka Server.
eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka

# Habilita a criação automática de rotas no Spring Cloud Gateway
# com base nos serviços registrados no Service Discovery (Eureka).
spring.cloud.gateway.discovery.locator.enabled=true

# Converte o ID do serviço registrado no Eureka para letras minúsculas
# ao gerar as rotas automaticamente no Gateway.
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Habilita endpoints específicos do Spring Cloud Gateway
management.endpoint.gateway.enabled=true

# Expõe explicitamente os endpoints do Actuator via HTTP
# Tomar cuidado ao expor esses endpoints em produção
management.endpoints.web.exposure.include=*

# Define o endpoint personalizado para acessar a interface do Swagger no navegador.
# Exemplo: http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html

# Define o nome que aparecerá no seletor no canto superior direito do Swagger UI.
springdoc.swagger-ui.urls[0].name=pedidos-api
# Define o caminho (path) onde o Gateway buscará o JSON de documentação do serviço de Pedidos.
springdoc.swagger-ui.urls[0].url=/pedidos-api/v3/api-docs

springdoc.swagger-ui.urls[1].name=pagamento-api
springdoc.swagger-ui.urls[1].url=/pagamento-api/v3/api-docs



