spring.application.name=gateway

# Porta em que a aplicação será executada.
server.port=8082

# URL do Eureka Server.
eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka

# Habilita a criação automática de rotas no Spring Cloud Gateway
# com base nos serviços registrados no Service Discovery (Eureka).
spring.cloud.gateway.discovery.locator.enabled=true

# Converte o ID do serviço registrado no Eureka para letras minúsculas
# ao gerar as rotas automaticamente no Gateway.
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Habilita endpoints específicos do Spring Cloud Gateway
management.endpoint.gateway.enabled=true

# Expõe explicitamente os endpoints do Actuator via HTTP
management.endpoints.web.exposure.include=*


